sudo: false

language: android

machine:
  environment:
    _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
    GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"

jdk:
- oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t build-tools-30.0.3
  - echo y | android update sdk -u -a -t android-30
  - echo y | android update sdk -u -a -t extra-android-support
  - echo y | android update sdk -u -a -t extra-android-m2repository

script: git submodule update --init --recursive && ./gradlew test && ./gradlew assemble

deploy:
  provider: releases
  api_key:
    secure: GX4AW/FE6Ruk0POOHMRAgpViFKi5PERe+d2MJQAg3Bcez5m2BbE0rCRJibBCpCiggQhcxa4BnL9BMOQTlnVs5M9u3nV5BoSHWM2IQRFhtZlmQaBm4kElPWUyi9B77WdLNo5boTuP6bQUsL1KQyiSlE2AS05VTt/6xqD5kfudd/9gCsdlZfx8gKb4zpH85K42LOtrZ8KLltLCtN5AHLhitQcJ2EQ6JQ+xn8TzIsxjFLAYY+5UVnmg+1Hx+tZ8M0Ghw6h+DRBKkARYrCK7DF04I3uNCAawtjOkharPOJHO6xytjChXcWYUq8nlSqc6hSUyJLlNl1RG/yHx6cddouK9Wc/4TP11cW0Bv4WvVzfKPtaTWSyXJp2yRh1ox0A8febjIH0Kgoest82qHvbN6yOBzoKoPGqAhrlB8ijOL5ZBksPw6c7zDmwloWqqGlWqq8a2WFnMelLa9MBBLFRoMx2KMjpdnlECyi2rqcVX54qPsQV3biruaPTR4rri46pdrjVD55d6Uv0KvEa5k4RmbRKi8Hp6VzMHBppkW6uCFCo6MwqkOeZxlHx+o6CjmDTedtJ1gcXyLDwaMpHxo/+Q5VGMKBEoY3u3A+0w/3PPkj4FntpiuTopoAKcM0SQsIUtkGuLvvMpC5OUKwtmeLeYO+sVouK9XdIJGLeWdCxp0x+8JiI=
  file: "./app/build/outputs/apk/release/*.apk"
  file_glob: true
  skip_cleanup: true
  on:
    repo: mathisdt/trackworktime
    tags: true
